### ISSUE TITLE
fite me

### ISSUE THREAD

**Issue by hwayne** [wgreenberg/beholder#1]
like a man

**Comment by wgreenberg** [comment]
_fights u but not in a gendered manner_

**Comment by hwayne** [comment]
uh i clearly meant fite me in a bare knuckle boxing match, the dominant fighting style from the isle of man

check ur assumptions maybe

**Comment by wgreenberg** [comment]
uhhhhhh actually if u knew ur Isle of Man Facts u'd know that such a style would be described as "like a [manx](https://en.wikipedia.org/wiki/Manx_people)"

read  a book perhaps
